keys:
  - &konstantin age13fjgxvdn5hhcvl8jwz9ysvc2hr66k6x63uf7z98pm906tpgg4qtq9n559p
creation_rules:
  - path_regex: .*/[^/]+.enc(\.yaml|\.json)?$
    key_groups:
      - age:
          - *konstantin

